---
title: "Data Analysis"
output: html_notebook
---
```{r libraries, warning=FALSE}
library(nhanesA) #importing NHANES data
library(dplyr) #manipulating data
library(purrr) #manipulating data
library(finalfit) #initial data analysis
library(caret) #ML workflows
library(randomForest)#Random Forest
library(naivebayes) #Naivebayes
library(glmnet)# LASSO regression
library(ggplot2)#visualisation
library(mice) #univariate imputation
library(NADIA) #reusing same univariate imputation on test data
library(plyr) #XGBoost
library(xgboost)#XGBoost
```

```{r PLEASE READ information about importing dataset and also chunks}
#importing datasets takes ~20 minutes
#running the entire file takes ~2-3 hours due to large dataset, imputation and cross validation

#Five Sections in each survey: 1. Demographics  2.Dietary [did not use this data as it is not relevant] 3.Examination  4.Laboratory  5.Questionnaire 
#sub-sections within sections and the respective questions extracted manually  from dataset based on theory  - see report appendix A for 25 variables extracted.

#####IF YOU RUN INTO ANY WARNINGS PLEASE IGNORE AND CONTINUE TO RUN SUBSEQUENT CHUNKS, THE VARIABLES ARE STILL SAVED#######
#it was due to my laptop memory running out when model training - if you get the same warnings please ignore, imputation also gives warning as single iteration on test data, though it works perfectly fine please ignore the chained warning.
```

```{r importing 1999-2000 NHANES data}
####Extracting relevant sub-section data for 1999-2000 Survey####
#Demographic section
D = nhanes('DEMO') #Demographic data

#Examination section
BP = nhanes('BPX') #Blood pressure data
BM = nhanes('BMX') #Body measures data

#Laboratory section
AL = nhanes('LAB16') # Albumin - Urine
LD = nhanes ('LAB13AM') #LDL Cholesterol
HD = nhanes ('LAB13') #HDL Cholesterol
GL = nhanes('LAB10') #Glycohemoglobin
PL = nhanes('LAB10AM') #Plasma Fasting Glucose & Insulin
PRO = nhanes('LAB18') #Biochemistry profile & Hormones
BL = nhanes('LAB25') #Blood profile

#Questionnaire section
ALQ = nhanes('ALQ') #Alcohol Use
DI = nhanes('DIQ') #Diabetes
DB = nhanes('DBQ') #Diet Behavior & Nutrition
KI = nhanes('KIQ') #Kidney Conditions
MC = nhanes('MCQ') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ') #Physical Activity
SM = nhanes('SMQ') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ') #Blood Pressure
CH = nhanes('CDQ') #Cardio Health


####Merging all sub-sections together based on sequence number of the survey####
survey_1999_2000 =
  list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  82 variables
survey_1999_2000 <- survey_1999_2000 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN, DMDYRSUS, DMDEDUC2,INDHHINC, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDL, URXUMASI, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ250A, DIQ080, KIQ020, PAD200, PAD320, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD090, MCQ010, MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHINC,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDL,
    Alb = URXUMASI,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ250A,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ020,
    Vig_Active = PAD200,
    Mod_Active = PAD320,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD090,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH)
```

```{r importing 2001-2002 NHANES data}
####Extracting relevant sub-section data for 2001-2002 Survey####
#Demographic section
D = nhanes('DEMO_B') #Demographic data

#Examination section
BP = nhanes('BPX_B') #Blood pressure data
BM = nhanes('BMX_B') #Body measures data

#Laboratory section
AL = nhanes('L16_B') # Albumin - Urine
LD = nhanes ('L13AM_B') #LDL Cholesterol
HD = nhanes ('L13_B') #HDL Cholesterol
GL = nhanes('L10_B') #Glycohemoglobin
PL = nhanes('L10AM_B') #Plasma Fasting Glucose & Insulin
PRO = nhanes('L40_B') #Biochemistry profile & Hormones
BL = nhanes('L25_B') #Blood profile

#Questionnaire section
ALQ = nhanes('ALQ_B') #Alcohol Use
DI = nhanes('DIQ_B') #Diabetes
DB = nhanes('DBQ_B') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_B') #Kidney Conditions
MC = nhanes('MCQ_B') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_B') #Physical Activity
SM = nhanes('SMQ_B') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_B') #Blood Pressure
CH = nhanes('CDQ_B') #Cardiovascular Health

####Merging all sub-sections together based on sequence number of the survey####
survey_2001_2002 =
  list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2001_2002 <- survey_2001_2002 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN, DMDYRSUS, DMDEDUC2,INDHHINC, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDL, URXUMASI, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ250A, DIQ080, KIQ022, PAD200, PAD320, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD090, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHINC,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDL,
    Alb = URXUMASI,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ250A,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAD200,
    Mod_Active = PAD320,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD090,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH)
```

```{r importing 2003-2004 NHANES data}
####Extracting relevant sub-section data for 2003-2004 Survey####
#Demographic section
D = nhanes('DEMO_C') #Demographic data

#Examination section
BP = nhanes('BPX_C') #Blood pressure data
BM = nhanes('BMX_C') #Body measures data

#Laboratory section
AL = nhanes('L16_C') # Albumin - Urine
LD = nhanes ('L13AM_C') #LDL Cholesterol
HD = nhanes ('L13_C') #HDL Cholesterol
GL = nhanes('L10_C') #Glycohemoglobin
PL = nhanes('L10AM_C') #Plasma Fasting Glucose & Insulin
PRO = nhanes('L40_C') #Biochemistry profile & Hormones
BL = nhanes('L25_C') #Blood profile

#Questionnaire section
ALQ = nhanes('ALQ_C') #Alcohol Use
DI = nhanes('DIQ_C') #Diabetes
DB = nhanes('DBQ_C') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_C') #Kidney Conditions
MC = nhanes('MCQ_C') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_C') #Physical Activity
SM = nhanes('SMQ_C') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_C') #Blood Pressure
CH = nhanes('CDQ_C') #Cardiovascular Health

####Merging all sub-sections together based on sequence number of the survey####
survey_2003_2004 =
  list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2003_2004 <- survey_2003_2004 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN, DMDYRSUS, DMDEDUC2,INDHHINC, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBXHDD, URXUMASI, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ250A, DIQ080, KIQ022, PAD200, PAD320, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD090, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHINC,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBXHDD,
    Alb = URXUMASI,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ250A,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAD200,
    Mod_Active = PAD320,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD090,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH)
```

```{r importing 2005-2006 NHANES data}
####Extracting relevant sub-section data for 2005-2006 Survey####
#Demographic section
D = nhanes('DEMO_D') #Demographic data

#Examination section
BP = nhanes('BPX_D') #Blood pressure data
BM = nhanes('BMX_D') #Body measures data

#Laboratory section
AL = nhanes('ALB_CR_D') # Albumin - Urine
LD = nhanes ('TRIGLY_D') #LDL Cholesterol
HD = nhanes ('HDL_D') #HDL Cholesterol
GL = nhanes('GHB_D') #Glycohemoglobin
PL = nhanes('GLU_D') #Plasma Fasting Glucose & Insulin
PRO = nhanes('BIOPRO_D') #Biochemistry profile & Hormones
BL = nhanes('CBC_D') #Blood profile

#Questionnaire section
ALQ = nhanes('ALQ_D') #Alcohol Use
DI = nhanes('DIQ_D') #Diabetes
DB = nhanes('DBQ_D') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_D') #Kidney Conditions
MC = nhanes('MCQ_D') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_D') #Physical Activity
SM = nhanes('SMQ_D') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_D') #Blood Pressure
CH = nhanes('CDQ_D') #Cardiovascular Health

####Merging all sub-sections together based on sequence number of the survey####
survey_2005_2006 =
  list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2005_2006 <- survey_2005_2006 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN, DMDYRSUS, DMDEDUC2,INDHHINC, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDD, URXUMS, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ300C, DIQ080, KIQ022, PAD200, PAD320, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD091, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHINC,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDD,
    Alb = URXUMS,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ300C,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAD200,
    Mod_Active = PAD320,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD091,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH)
```

```{r importing 2007-2008 NHANES data}
####Extracting relevant sub-section data for 2007-2008 Survey####
#Demographic section
D = nhanes('DEMO_E') #Demographic data

#Examination section
BP = nhanes('BPX_E') #Blood pressure data
BM = nhanes('BMX_E') #Body measures data

#Laboratory section
AL = nhanes('ALB_CR_E') # Albumin - Urine
LD = nhanes ('TRIGLY_E') #LDL Cholesterol
HD = nhanes ('HDL_E') #HDL Cholesterol
GL = nhanes('GHB_E') #Glycohemoglobin
PL = nhanes('GLU_E') #Plasma Fasting Glucose & Insulin
PRO = nhanes('BIOPRO_E') #Biochemistry profile & Hormones
BL = nhanes('CBC_E') #Blood profile


#Questionnaire section
ALQ = nhanes('ALQ_E') #Alcohol Use
DI = nhanes('DIQ_E') #Diabetes
DB = nhanes('DBQ_E') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_E') #Kidney Conditions
MC = nhanes('MCQ_E') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_E') #Physical Activity
SM = nhanes('SMQ_E') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_E') #Blood Pressure
CH = nhanes('CDQ_E') #Cardiovascular Health

####Merging all together based on sequence number of the survey####
survey_2007_2008 =list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2007_2008 <- survey_2007_2008 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN2, DMDYRSUS, DMDEDUC2,INDHHIN2, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDD, URXUMS, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ300C, DIQ080, KIQ022, PAQ650, PAQ665, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD895, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN2,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHIN2,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDD,
    Alb = URXUMS,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ300C,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAQ650,
    Mod_Active = PAQ665,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD895,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )

####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH)
```

```{r importing 2009-2010 NHANES data}
####Extracting relevant sub-section data for 2009-2010 Survey####
#Demographic section
D = nhanes('DEMO_F') #Demographic data

#Examination section
BP = nhanes('BPX_F') #Blood pressure data
BM = nhanes('BMX_F') #Body measures data

#Laboratory section
AL = nhanes('ALB_CR_F') # Albumin - Urine
LD = nhanes ('TRIGLY_F') #LDL Cholesterol
HD = nhanes ('HDL_F') #HDL Cholesterol
GL = nhanes('GHB_F') #Glycohemoglobin
PL = nhanes('GLU_F') #Plasma Fasting Glucose & Insulin
PRO = nhanes('BIOPRO_F') #Biochemistry profile & Hormones
BL = nhanes('CBC_F') #Blood profile


#Questionnaire section
ALQ = nhanes('ALQ_F') #Alcohol Use
DI = nhanes('DIQ_F') #Diabetes
DB = nhanes('DBQ_F') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_F') #Kidney Conditions
MC = nhanes('MCQ_F') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_F') #Physical Activity
SM = nhanes('SMQ_F') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_F') #Blood Pressure
CH = nhanes('CDQ_F') #Cardiovascular Health


####Merging all together based on sequence number of the survey####
survey_2009_2010 =list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2009_2010 <- survey_2009_2010 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN2, DMDYRSUS, DMDEDUC2,INDHHIN2, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDD, URXUMS, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ300C, DIQ080, KIQ022, PAQ650, PAQ665, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD895, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN2,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHIN2,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDD,
    Alb = URXUMS,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ300C,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAQ650,
    Mod_Active = PAQ665,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD895,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH)
```

```{r importing 2011-2012 NHANES data}
####Extracting relevant sub-section data for 2011-2012 Survey####
#Demographic section
D = nhanes('DEMO_G') #Demographic data

#Examination section
BP = nhanes('BPX_G') #Blood pressure data
BM = nhanes('BMX_G') #Body measures data

#Laboratory section
AL = nhanes('ALB_CR_G') # Albumin - Urine
LD = nhanes ('TRIGLY_G') #LDL Cholesterol
HD = nhanes ('HDL_G') #HDL Cholesterol
GL = nhanes('GHB_G') #Glycohemoglobin
PL = nhanes('GLU_G') #Plasma Fasting Glucose & Insulin
PRO = nhanes('BIOPRO_G') #Biochemistry profile & Hormones
BL = nhanes('CBC_G') #Blood profile


#Questionnaire section
ALQ = nhanes('ALQ_G') #Alcohol Use
DI = nhanes('DIQ_G') #Diabetes
DB = nhanes('DBQ_G') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_G') #Kidney Conditions
MC = nhanes('MCQ_G') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_G') #Physical Activity
SM = nhanes('SMQ_G') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_G') #Blood Pressure
CH = nhanes('CDQ_G') #Cardiovascular Health


####Merging all together based on sequence number of the survey####
survey_2011_2012 =list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2011_2012 <- survey_2011_2012 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN4, DMDYRSUS, DMDEDUC2,INDHHIN2, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDD, URXUMS, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ300C, DIQ080, KIQ022, PAQ650, PAQ665, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD895, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN4,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHIN2,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDD,
    Alb = URXUMS,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ300C,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAQ650,
    Mod_Active = PAQ665,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD895,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH)
```

```{r importing 2013-2014 NHANES data}
####Extracting relevant sub-section data for 2013-2014 Survey####
#Demographic section
D = nhanes('DEMO_H') #Demographic data

#Examination section
BP = nhanes('BPX_H') #Blood pressure data
BM = nhanes('BMX_H') #Body measures data

#Laboratory section
AL = nhanes('ALB_CR_H') # Albumin - Urine
LD = nhanes ('TRIGLY_H') #LDL Cholesterol
HD = nhanes ('HDL_H') #HDL Cholesterol
GL = nhanes('GHB_H') #Glycohemoglobin
PL = nhanes('GLU_H') #Plasma Fasting Glucose
I = nhanes('INS_H') #Insulin
PRO = nhanes('BIOPRO_H') #Biochemistry profile & Hormones
BL = nhanes('CBC_H') #Blood profile


#Questionnaire section
ALQ = nhanes('ALQ_H') #Alcohol Use
DI = nhanes('DIQ_H') #Diabetes
DB = nhanes('DBQ_H') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_H') #Kidney Conditions
MC = nhanes('MCQ_H') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_H') #Physical Activity
SM = nhanes('SMQ_H') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_H') #Blood Pressure
CH = nhanes('CDQ_H') #Cardiovascular Health


####Merging all together based on sequence number of the survey####
survey_2013_2014 =list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH,I) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2013_2014 <- survey_2013_2014 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN4, DMDYRSUS, DMDEDUC2,INDHHIN2, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDD, URXUMS, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ300C, DIQ080, KIQ022, PAQ650, PAQ665, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD895, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN4,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHIN2,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDD,
    Alb = URXUMS,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ300C,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAQ650,
    Mod_Active = PAQ665,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD895,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH,I)
```

```{r importing 2015-2016 NHANES data}
####Extracting relevant sub-section data for 2015-2016 Survey####
#Demographic section
D = nhanes('DEMO_I') #Demographic data

#Examination section
BP = nhanes('BPX_I') #Blood pressure data
BM = nhanes('BMX_I') #Body measures data

#Laboratory section
AL = nhanes('ALB_CR_I') # Albumin - Urine
LD = nhanes ('TRIGLY_I') #LDL Cholesterol
HD = nhanes ('HDL_I') #HDL Cholesterol
GL = nhanes('GHB_I') #Glycohemoglobin
PL = nhanes('GLU_I') #Plasma Fasting Glucose
I = nhanes('INS_I') #Insulin
PRO = nhanes('BIOPRO_I') #Biochemistry profile & Hormones
BL = nhanes('CBC_I') #Blood profile


#Questionnaire section
ALQ = nhanes('ALQ_I') #Alcohol Use
DI = nhanes('DIQ_I') #Diabetes
DB = nhanes('DBQ_I') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_I') #Kidney Conditions
MC = nhanes('MCQ_I') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_I') #Physical Activity
SM = nhanes('SMQ_I') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_I') #Blood Pressure
CH = nhanes('CDQ_I') #Cardiovascular Health


####Merging all together based on sequence number of the survey####
survey_2015_2016 =list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH,I) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2015_2016 <- survey_2015_2016 %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN4, DMDYRSUS, DMDEDUC2,INDHHIN2, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDD, URXUMS, LBXGH,
                LBXGLU,LBXIN, ALQ120Q, DIQ010, MCQ300C, DIQ080, KIQ022, PAQ650, PAQ665, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD895, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN4,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHIN2,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDD,
    Alb = URXUMS,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ120Q,
    Diabetes = DIQ010,
    Fam_History = MCQ300C,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAQ650,
    Mod_Active = PAQ665,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD895,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH,I)
```

```{r importing 2017-2018 NHANES data}
####Extracting relevant sub-section data for 2015-2016 Survey####
#Demographic section
D = nhanes('DEMO_J') #Demographic data

#Examination section
BP = nhanes('BPX_J') #Blood pressure data
BM = nhanes('BMX_J') #Body measures data

#Laboratory section
AL = nhanes('ALB_CR_J') # Albumin - Urine
LD = nhanes ('TRIGLY_J') #LDL Cholesterol
HD = nhanes ('HDL_J') #HDL Cholesterol
GL = nhanes('GHB_J') #Glycohemoglobin
PL = nhanes('GLU_J') #Plasma Fasting Glucose
I = nhanes('INS_J') #Insulin
PRO = nhanes('BIOPRO_J') #Biochemistry profile & Hormones
BL = nhanes('CBC_J') #Blood profile


#Questionnaire section
ALQ = nhanes('ALQ_J') #Alcohol Use
DI = nhanes('DIQ_J') #Diabetes
DB = nhanes('DBQ_J') #Diet Behavior & Nutrition
KI = nhanes('KIQ_U_J') #Kidney Conditions
MC = nhanes('MCQ_J') #Medical Conditions - family history of diabetes
PH = nhanes('PAQ_J') #Physical Activity
SM = nhanes('SMQ_J') #Smoking - Cigarette/Tobacco Use - Adult
BPQ = nhanes('BPQ_J') #Blood Pressure
CH = nhanes('CDQ_J') #Cardiovascular Health


####fixing join error for survey 2017-2018####
D  <- D %>%  
    mutate(SEQN = as.numeric(SEQN))

BP  <- BP %>%  
    mutate(SEQN = as.numeric(SEQN))

BM  <- BM %>%  
    mutate(SEQN = as.numeric(SEQN))

AL  <- AL %>%  
    mutate(SEQN = as.numeric(SEQN))

LD  <- LD %>%  
    mutate(SEQN = as.numeric(SEQN))

HD  <- HD %>%  
    mutate(SEQN = as.numeric(SEQN))

GL  <- GL %>%  
    mutate(SEQN = as.numeric(SEQN))

PL  <- PL %>%  
    mutate(SEQN = as.numeric(SEQN))

PRO  <- PRO %>%  
    mutate(SEQN = as.numeric(SEQN))

I  <- I %>%  
    mutate(SEQN = as.numeric(SEQN))

BL  <- BL %>%  
    mutate(SEQN = as.numeric(SEQN))

ALQ  <- ALQ %>%  
    mutate(SEQN = as.numeric(SEQN))

DI  <- DI %>%  
    mutate(SEQN = as.numeric(SEQN))

DB  <- DB %>%  
    mutate(SEQN = as.numeric(SEQN))

KI  <- KI %>%  
    mutate(SEQN = as.numeric(SEQN))

MC   <- MC %>%  
    mutate(SEQN = as.numeric(SEQN))

PH  <- PH %>%  
    mutate(SEQN = as.numeric(SEQN))

SM  <- SM %>%  
    mutate(SEQN = as.numeric(SEQN))

CH  <- CH %>%  
    mutate(SEQN = as.numeric(SEQN))

BPQ  <- BPQ %>%  
    mutate(SEQN = as.numeric(SEQN))


####Merging all together based on sequence number of the survey####
survey_2017_2018 =list(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH,I) %>% 
  purrr::reduce(full_join, by = "SEQN") 

###Selecting relevant questions from sub-sections###  75 variables
survey_2017_2018  <- survey_2017_2018  %>% 
  dplyr::select(RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN4, DMDYRSUS, DMDEDUC2,INDHHIN2, BPXSY1, BPXDI1, BMXWT, BMXHT, BMXBMI, BMXARMC, BMXARML, BMXLEG, BMXWAIST, LBDLDL, LBDHDD, URXUMS, LBXGH,
                LBXGLU,LBXIN, ALQ121, DIQ010, MCQ300C, DIQ080, KIQ022, PAQ650, PAQ665, SMQ040, MCQ160B, MCQ160C, MCQ160F, MCQ160E,DMDMARTL, INDFMPIR, DMDHHSIZ, BPXSY2, BPXSY3, BPXDI2,
                BPXDI3, BMXHEAD, LBXSOSSI, LBXSBU, LBXSCA, LBXSCH, LBXSGL, LBXSATSI,  LBXSASSI, LBXSC3SI,  LBXSGTSI, LBXSIR, LBDSTPSI, LBXSTR, LBXSUA,
                LBXSNASI,  LBXSKSI, LBXSCLSI, LBDSGBSI, LBXWBCSI,  LBXRBCSI,  LBXHGB, LBXMCVSI, LBXMCHSI, LBXPLTSI, LBXMPSI, BPQ020, CDQ010, DIQ050, DBD895, MCQ010,
                MCQ160A, MCQ080, SMQ020, SMD057) %>%
  dplyr::rename(
    Gender = RIAGENDR,
    Age = RIDAGEYR,
    Ethnicity = RIDRETH1,
    Country_Birth = DMDBORN4,
    Time_US = DMDYRSUS,
    Education_level = DMDEDUC2,
    Income = INDHHIN2,
    BP_Sys = BPXSY1,
    BP_Dia = BPXDI1,
    Weight = BMXWT,
    Height = BMXHT,
    BMI = BMXBMI,
    Arm_Cir = BMXARMC,
    Up_Arm_Len = BMXARML,
    Up_Leg_Len = BMXLEG,
    Wasit_Cir = BMXWAIST,
    LDL_Chol = LBDLDL,
    HDL_Chol = LBDHDD,
    Alb = URXUMS,
    Glyco = LBXGH,
    Fast_Glu = LBXGLU,
    Insulin = LBXIN,
    Alcohol = ALQ121,
    Diabetes = DIQ010,
    Fam_History = MCQ300C,
    Eye_Issue = DIQ080,
    Bad_Kidneys = KIQ022,
    Vig_Active = PAQ650,
    Mod_Active = PAQ665,
    Smoking = SMQ040,
    Cong_Heart_Fail = MCQ160B,
    Cor_Heart_Dis = MCQ160C,
    Stroke = MCQ160F,
    Heart_Attack = MCQ160E, 
    Marital = DMDMARTL, 
    Fam_PIR = INDFMPIR, 
    Num_House = DMDHHSIZ, 
    BP_Sys2 = BPXSY2, 
    BP_Sys3 = BPXSY3, 
    BP_Dia2 = BPXDI2,
    BP_Dia3 = BPXDI3,
    Head_Cir = BMXHEAD,
    B_Osmolality = LBXSOSSI, 
    BUN = LBXSBU, 
    T_Ca = LBXSCA, 
    T_Chol = LBXSCH, 
    T_Glu_Ser = LBXSGL, 
    ALT = LBXSATSI,  
    AST = LBXSASSI,  
    BiCarb = LBXSC3SI,  
    GGT = LBXSGTSI, 
    Fe = LBXSIR, 
    Protein = LBDSTPSI, 
    Triglyc = LBXSTR, 
    Uric = LBXSUA,
    Na = LBXSNASI,
    K = LBXSKSI,
    Cl = LBXSCLSI,
    Globulin = LBDSGBSI, 
    W_Blood_Count = LBXWBCSI,  
    R_Blood_Count = LBXRBCSI,  
    Hemoglobin = LBXHGB,
    M_Cell_Vol = LBXMCVSI, 
    M_Cell_Hemo = LBXMCHSI, 
    Plate_Count = LBXPLTSI, 
    M_Plate_Vol = LBXMPSI, 
    Dr_BP = BPQ020, 
    Short_Breath = CDQ010, 
    Now_Insulin = DIQ050, 
    Num_Food_Outside = DBD895,
    Dr_Asthma = MCQ010, 
    Dr_Arthritis = MCQ160A, 
    Dr_Overweight = MCQ080, 
    Min_100_Smoke = SMQ020, 
    Num_Smoke_Quit = SMD057
    )


####removing sub-section data from r to clear space for other survey imports####
rm(D,BP,BM,AL,LD,HD,GL,PL,PRO,BL,ALQ,DI,DB,KI,MC,PH,SM, BPQ,CH,I)
```

```{r merging all surveys together 1999-2018}
#merging surveys together
combined <- do.call("rbind", list(survey_1999_2000,survey_2001_2002,survey_2003_2004,
                     survey_2005_2006,survey_2007_2008,survey_2009_2010,
                     survey_2011_2012,survey_2013_2014,survey_2015_2016,
                     survey_2017_2018))

#remove surveys (can comment if need them)
rm(survey_1999_2000,survey_2001_2002,survey_2003_2004,
                     survey_2005_2006,survey_2007_2008,survey_2009_2010,
                     survey_2011_2012,survey_2013_2014,survey_2015_2016,
                     survey_2017_2018)
```

```{r handling missing data p1 and data transformations}
##### - Missing data handling - #####
#showing percent of missing values in each column
print(colMeans(is.na(combined))*100)

#removing columns (variables) with more than 25% missingness (25 variables remain)
combined25 = combined[, which(colMeans(!is.na(combined)) >= 0.75)]

#making sure variables are coded correctly
combined25 %>% 
  ff_glimpse()

#variable type of all columns are incorrect (all data type is classed as labelled), converting to proper variable type
#converting continuous factors to numeric
combined25$Age <- as.numeric(as.character(combined25$Age))
combined25$Weight <- as.numeric(as.character(combined25$Weight))
combined25$BMI <- as.numeric(as.character(combined25$BMI))
combined25$Height <- as.numeric(as.character(combined25$Height))
combined25$Arm_Cir <- as.numeric(as.character(combined25$Arm_Cir))
combined25$Up_Arm_Len <- as.numeric(as.character(combined25$Up_Arm_Len))
combined25$Wasit_Cir <- as.numeric(as.character(combined25$Wasit_Cir))
combined25$Alb <- as.numeric(as.character(combined25$Alb))
combined25$Fam_PIR <- as.numeric(as.character(combined25$Fam_PIR))
combined25$Num_House <- as.numeric(as.character(combined25$Num_House))
combined25$W_Blood_Count <- as.numeric(as.character(combined25$W_Blood_Count))
combined25$R_Blood_Count <- as.numeric(as.character(combined25$R_Blood_Count))
combined25$Hemoglobin <- as.numeric(as.character(combined25$Hemoglobin))
combined25$M_Cell_Vol <- as.numeric(as.character(combined25$M_Cell_Vol))
combined25$M_Cell_Hemo <- as.numeric(as.character(combined25$M_Cell_Hemo))
combined25$Plate_Count <- as.numeric(as.character(combined25$Plate_Count))
combined25$M_Plate_Vol <- as.numeric(as.character(combined25$M_Plate_Vol))

#converting categorical factors to factors
combined25$Gender <- as.factor(as.character(combined25$Gender))
combined25$Ethnicity <- as.factor(as.character(combined25$Ethnicity))
combined25$Country_Birth <- as.factor(as.character(combined25$Country_Birth))
combined25$Income <- as.factor(as.character(combined25$Income))
combined25$Diabetes <- as.factor(as.character(combined25$Diabetes))
combined25$Now_Insulin <- as.factor(as.character(combined25$Now_Insulin))
combined25$Num_Food_Outside <- as.factor(as.character(combined25$Num_Food_Outside))
combined25$Dr_Asthma <- as.factor(as.character(combined25$Dr_Asthma))


#convert % to numeric for Plate_Count
combined25$Plate_Count <- (combined25$Plate_Count)/100


##### - Transforming categorical data levels into meaningful labels - #####
levels(combined25$Gender) <- list("Male" = "1", "Female" = "2")

levels(combined25$Ethnicity) <- list("Mexican American" = "1", "Other Hispanic" = "2","Non-Hispanic White" = "3", "Non-Hispanic Black" = "4", "Other Race" = "5")

levels(combined25$Country_Birth) <- list("USA" = "1", "Mexico" = "2","Other Country" = c("4", "5"), "Delete" = c("7","9","(Missing)"))

#https://money.usnews.com/money/personal-finance/family-finance/articles/where-do-i-fall-in-the-american-economic-class-system 
levels(combined25$Income) <- list("$0-$34.9K" = c("1","2", "3", "4", "5", "6"), "$35K to $54.9K" = c("7","8"),
                                  "$55K to $99.9K" = c("9", "10", "14"), "$100K+" = "15","Delete" = c("(Missing)", "77", "99", "12","13"))

levels(combined25$Diabetes) <- list("Diabetic" = c("1","3"), "Non-Diabetic" = "2", "Delete" = c("7", "9","(Missing)")) 

levels(combined25$Now_Insulin) <- list("Yes" = "1", "No" = "2", "Delete" = c("7", "9","(Missing)"))

levels(combined25$Num_Food_Outside) <- list("1-21" = c("1","2","3", "4", "5", "6" ,"7","8","9","10",
                                                       "11","12","13","14", "15","16","17","18","19","20","21","6666"), "None" = "0", "21+" = c("5555","26"), 
                                            "Delete" = c("7777", "9999","(Missing)"))

levels(combined25$Dr_Asthma) <- list("Asthmatic" = "1","Not-Asthmatic" = "2","Delete" = c("7", "9","(Missing)"))


#dropping 'refused','don't know' and other meaningless responses in variables
is.na(combined25$Country_Birth) <- combined25$Country_Birth == "Delete" 
combined25$Country_Birth <- droplevels(combined25$Country_Birth)

is.na(combined25$Income) <- combined25$Income == "Delete" 
combined25$Income <- droplevels(combined25$Income)

is.na(combined25$Diabetes) <- combined25$Diabetes == "Delete" 
combined25$Diabetes <- droplevels(combined25$Diabetes)

is.na(combined25$Now_Insulin) <- combined25$Now_Insulin == "Delete" 
combined25$Now_Insulin <- droplevels(combined25$Now_Insulin)

is.na(combined25$Num_Food_Outside) <- combined25$Num_Food_Outside == "Delete" 
combined25$Num_Food_Outside <- droplevels(combined25$Num_Food_Outside)

is.na(combined25$Dr_Asthma) <- combined25$Dr_Asthma == "Delete" 
combined25$Dr_Asthma <- droplevels(combined25$Dr_Asthma)

#moving diabetes (DV) to first column
combined25 <- combined25 %>%
  dplyr::select(Diabetes, everything())

str(combined25)

#101,316 x 25 
```

```{r splitting data}
set.seed(2021) #setting seed

#80% training, 20% test (stratified random sample)
training_sub <- combined25$Diabetes %>% 
  createDataPartition(p = 0.8, list = FALSE)

train_dat  <- combined25[training_sub, ]
test_dat <- combined25[-training_sub, ]

```

```{r handling missing data p2 univariate imputation}
#NOTE:takes ~10 minutes to run this chunk

#####IF YOU RUN INTO ANY WARNINGS PLEASE IGNORE AND CONTINUE TO RUN SUBSEQUENT CHUNKS, THE VARIABLES ARE STILL SAVED#######

#data is MAR - "probability of a missing observation can be explained by the observed data"

#univariate imputation - utilises: predictive mean matching for numeric variables, logit for binary variables, multinomial logit for nominal >2 levels and ordered logit for ordered var >2 levels.
#(5 gibbs sampling iterations)
D_imp_train <- mice(train_dat,m=1, maxit=5, printFlag = FALSE, seed = 2021)
D_imp_trainC <- mice::complete(D_imp_train)

# #inspecting convergence
# plot(D_imp_trainC) #lines are free from trends and intermingling
# 
# #inspecting if imputed values have similar distribution as observed
# stripplot(imp_trainC$Diabetes)

#imputing test data based on the same training imputation model  - prevents information leakage
imp_test <- NADIA::mice.reuse(D_imp_train, test_dat, maxit = 1,printFlag = FALSE, seed = 2021)
imp_testC <- imp_test[[1]]
```

```{r downsampling}
# #using downsampling to balance diabetes dependent variable on training dataset
#original training table = >1:10 class imbalanace
set.seed(2021)
table(D_imp_trainC$Diabetes)

downsamp_train <- downSample(x = D_imp_trainC[,-1],
                    y = D_imp_trainC$Diabetes,
                    yname="Diabetes")

#downsamples training table
table(downsamp_train$Diabetes)

#moving diabetes (DV) to first column
downsamp_train <- downsamp_train %>%
  dplyr::select(Diabetes, everything())

str(downsamp_train)
```

```{r dumming coding and standardising}
###DUMMY CODING - dummy code on  train and test data separately  - prevents information leakage
#dummy code  IVs 
D_Xtrain <- model.matrix(Diabetes~., downsamp_train)[,-1]
D_Xtest <- model.matrix(Diabetes~., imp_testC)[,-1]

#numeric conversion of DV - 
D_Ytrain <- ifelse(downsamp_train$Diabetes == "Diabetic", 1, 0)
D_Ytrain <- as.factor(as.character(D_Ytrain))
#performance metrics: balanced accuray, P/R, F1

###STANDARDISATION
#standardisng variables in training set 
D_vals_preproc <- caret::preProcess(D_Xtrain, method = c("center", "scale"))

D_scaledDummy_Xtrain <- predict(D_vals_preproc, D_Xtrain)

#using calculations from training set to standardise variables in the test set  - prevents information leakage
D_scaledDummy_Xtest <- predict(D_vals_preproc, D_Xtest)
```

```{r lasso logit regression}
#using 10 fold CV for finding best lambda&model fit
set.seed(2021)
fit_lassologit <- cv.glmnet(x=D_scaledDummy_Xtrain, y = D_Ytrain, family = "binomial", alpha = 1, nfolds = 10, standardize = FALSE)

#plot CV error of log lambda, in graph log of optimal lambda is approx
plot(fit_lassologit, xlab="Log Lambda", ylab = "Cross validation error")
#26 variables included in lowest CV error (not including intercept)

#optimal lamba value
fit_lassologit$lambda.min

```

```{r lasso logit regression p2}
set.seed(2021)

#extracting predictions and class probabilities
prob_lassolog <- predict(fit_lassologit, newx = D_scaledDummy_Xtest, s = "lambda.min", type = "response") #probabilities
pred_lassolog <- ifelse(prob_lassolog >0.5, "Diabetic", "Non-Diabetic") #predicted values

D_actual <- imp_testC$Diabetes #actual values

#confusion matrix
confusionMatrix((factor(pred_lassolog)),(factor(D_actual)))
```

```{r important variables}
coef(fit_lassologit, s = fit_lassologit$lambda.min)

#26 variables important
```

```{r converting from dataframes to matrices}

#data: = D_scaledDummy_Xtrain =train IVs, #D_Ytrain = train DV, #D_scaledDummy_Xtest = test IV, #D_actual = test DV

#converting to dataframe from matrix for later models
D_scaledDummy_XtestM <- as.data.frame(D_scaledDummy_Xtest)
D_scaledDummy_XtrainM <- as.data.frame(D_scaledDummy_Xtrain)

#using reduced variables found from feature selection on test set
RD_scaledDummy_XtestM <- D_scaledDummy_XtestM %>%
  dplyr::select(-c("M_Cell_Hemo", "Hemoglobin", "BMI", "Income$35K to $54.9K", "Country_BirthMexico"))

RD_scaledDummy_XtestM <- as.matrix(RD_scaledDummy_XtestM )

RD_scaledDummy_XtrainM <- D_scaledDummy_XtrainM %>%
  dplyr::select(-c("M_Cell_Hemo", "Hemoglobin", "BMI", "Income$35K to $54.9K", "Country_BirthMexico"))

# #test (ignore)
# D_scaledDummy_Fulltrain <- cbind(downsamp_train$Diabetes,D_scaledDummy_Xtrain)
# D_scaledDummy_FulltrainM <- as.data.frame(D_scaledDummy_Fulltrain)
# RD_scaledDummy_FulltrainM <- D_scaledDummy_FulltrainM  %>%
#   dplyr::rename("Diabetes" = "V1") %>%
#   dplyr::select(-c("M_Cell_Hemo", "Hemoglobin", "BMI", "Income$35K to $54.9K", "Country_BirthMexico"))
# RD_scaledDummy_FulltrainM$Diabetes <- as.factor(as.character(RD_scaledDummy_FulltrainM$Diabetes))
```

```{r Random Forest model}
#NOTE: runtime ~10 minutes

#####IF YOU RUN INTO ANY WARNINGS PLEASE IGNORE AND CONTINUE TO RUN SUBSEQUENT CHUNKS, THE VARIABLES ARE STILL SAVED#######

#parameters to tune
#mtry

#creating 5 fold CV  (too large dataset to do anymore folds or repeated CV) using gridsearch 

#not enough computer memory (however model still returns fine)
control <- trainControl(method = 'cv', number = 5, search = 'grid', allowParallel = FALSE)

#creating data frame with possible tuning values for mtry parameters
tuning_grid <- expand.grid(.mtry=c(4,6,7,8))

#training with various ntrees
set.seed(2021)
rf_fit <- train(x = RD_scaledDummy_XtrainM,
                y = D_Ytrain,
                method = "rf", 
                metric = 'Accuracy', 
                tuneGrid = tuning_grid, 
                trControl = control,
                ntree = 500)


rf_fit$finalModel

#best mtry = 5
```

```{r Random Forest p2}
set.seed(2021)

#extracting predictions and class probabilities
pred_rf <- caret::predict.train(object=rf_fit, RD_scaledDummy_XtestM, type = "raw") #predictions
pred_rf2 <- ifelse(pred_rf == "1", "Diabetic", "Non-Diabetic") #predicted values

D_actual <- imp_testC$Diabetes #actual values

#confusion-matrix

confusionMatrix(factor(pred_rf2),factor(D_actual))

```

```{r Naive Bayes Model}
#####IF YOU RUN INTO ANY WARNINGS PLEASE IGNORE AND CONTINUE TO RUN SUBSEQUENT CHUNKS, THE VARIABLES ARE STILL SAVED#######

#Parameters to tune
# laplace (Laplace Correction)
# usekernel (Distribution Type)
# adjust (bandwidth adjustment)


#creating 5 fold CV  (too large dataset to do anymore folds or repeated CV) using gridsearch #not enough computer memory 
controlnb <- trainControl(method = 'cv', number = 5, search = 'grid', allowParallel=FALSE)

#creating data frame with possible tuning values for  parameters
tuning_gridnb <- expand.grid(laplace=c(0,0.5,1), usekernel=c(TRUE,FALSE), adjust=c(0.5, 1, 1.5,3.0))

#training with various ntrees
set.seed(2021)
nb_fit <- train(x = RD_scaledDummy_XtrainM,
                y = D_Ytrain, 
                method = "naive_bayes", 
                metric = 'Accuracy', 
                tuneGrid = tuning_gridnb, 
                trControl = controlnb,
                usepoisson = TRUE)


# Selected tuning parameters
nb_fit$finalModel$tuneValue

#best model
nb_fit$finalModel
```

```{r Naive Bayes Model p2}
set.seed(2021)
#extracting predictions and class probabilities
pred_nb <- caret::predict.train(object=nb_fit, RD_scaledDummy_XtestM, type = "raw") #predictions
pred_nb2 <- ifelse(pred_nb == "1", "Diabetic", "Non-Diabetic") #predicted values

D_actual <- imp_testC$Diabetes #actual values

#confusion-matrix

confusionMatrix(factor(pred_nb2),factor(D_actual))

```

```{r XGBoost Model}
#NOTE: takes ~1 hour to run

#####IF YOU RUN INTO ANY WARNINGS PLEASE IGNORE AND CONTINUE TO RUN SUBSEQUENT CHUNKS, THE VARIABLES ARE STILL SAVED#######

#Parameters to tune
# nrounds ( Boosting Iterations)
# max_depth (Max Tree Depth)
# eta (Shrinkage)
# gamma (Minimum Loss Reduction)
# colsample_bytree (Subsample Ratio of Columns)
# min_child_weight (Minimum Sum of Instance Weight)
# subsample (Subsample Percentage)

#creating 5 fold CV  (too large dataset to do anymore folds or repeated CV) using gridsearch #not enough computer memory 
controlxgb <- trainControl(method = 'cv', number = 5, search = 'grid', allowParallel = FALSE)

#creating data frame with possible tuning values for parameters
tuning_gridxgb <- expand.grid(
  nrounds = seq(from = 200, to = 1000, by = 50),
  eta = c(0.025, 0.05, 0.1, 0.3),
  max_depth = seq(from=2, to=24, by=2),
  gamma = 0,
  colsample_bytree = 1,
  min_child_weight = 1,
  subsample = 1
)

#training with various ntrees
set.seed(2021)
xgb_fit <- train(x = RD_scaledDummy_XtrainM,
                y = D_Ytrain, 
                method = 'xgbTree', 
                metric = 'Accuracy', 
                tuneGrid = tuning_gridxgb, 
                trControl = controlxgb)
#best parameters
xgb_fit$bestTune

#best model
xgb_fit$finalModel
```

```{r XGBoost Model p2}
set.seed(2021)
#extracting predictions and class probabilities
pred_xgb <- caret::predict.train(object=xgb_fit, RD_scaledDummy_XtestM, type = "raw") #predictions
pred_xgb2 <- ifelse(pred_rf == "1", "Diabetic", "Non-Diabetic") #predicted values

D_actual <- imp_testC$Diabetes #actual values

#confusion-matrix

confusionMatrix(factor(pred_xgb2),factor(D_actual))

```


#NOT DOWNSAMPLED DATA (comparison)

```{r Not Downsampled: handling missing data p2 univariate imputation}
#NOTE:takes approximately 30 minutes

#data is MAR - "probability of a missing observation can be explained by the observed data"

#univariate imputation - utilises: predictive mean matching for numeric variables, logit for binary variables, multinomial logit for nominal >2 levels and ordered logit for ordered var >2 levels.
#(5 gibbs sampling iterations)
N_imp_train <- mice(train_dat,m=1, maxit=10, printFlag = FALSE, seed = 123)
N_imp_trainC <- mice::complete(N_imp_train)

# #inspecting convergence
# plot(N_imp_trainC) #lines are free from trends and intermingling
# 
# #inspecting if imputed values have similar distribution as observed
# stripplot(N_imp_trainC$Diabetes)


#imputing test data based on the same training imputation model  - prevents information leakage
N_imp_test <- NADIA::mice.reuse(N_imp_train, test_dat, maxit = 1,printFlag = FALSE, seed = 123)
N_imp_testC <- N_imp_test[[1]]
```

```{r Not Downsampled: dumming coding and standardising}
###DUMMY CODING - dummy code on  train and test data separately  - prevents information leakage
#dummy code  IVs 
N_Xtrain <- model.matrix(Diabetes~., N_imp_trainC)[,-1]
N_Xtest <- model.matrix(Diabetes~., N_imp_testC)[,-1]

#numeric conversion of DV - 
N_Ytrain <- ifelse(N_imp_trainC$Diabetes == "Diabetic", 1, 0)

#performance metrics: balanced accuray, P/R, F1

###STANDARDISATION
#standardisng variables in training set 
N_vals_preproc <- caret::preProcess(N_Xtrain, method = c("center", "scale"))

N_scaledDummy_Xtrain <- predict(N_vals_preproc, N_Xtrain)

#using calculations from training set to standardise numerical variables in the test set  - prevents information leakage
N_scaledDummy_Xtest <- predict(N_vals_preproc, N_Xtest)
```

```{r Not Downsampled: lasso regression}
#using 5 fold CV for finding best lambda&model fit
set.seed(123)
N_fit_lassologit <- cv.glmnet(x=N_scaledDummy_Xtrain, y = N_Ytrain, family = "binomial", alpha = 1, nfolds = 5, standardize = FALSE)

#plot CV error of log lambda, in graph log of optimal lambda is approx
plot(N_fit_lassologit, xlab="Log Lambda", ylab = "Cross validation error")

#optimal lamba value
N_fit_lassologit $lambda.min

```

```{r Not Downsampled: lasso regression p2}
set.seed(123)

#predicting test data
N_prob_lassolog <- predict(N_fit_lassologit, newx = N_scaledDummy_Xtest, s = "lambda.min", type = "response") #probabilities
N_pred_lassolog <- ifelse(N_prob_lassolog >0.5, "Diabetic", "Non-Diabetic") #predicted values

N_actual <- N_imp_testC$Diabetes #actual values

#confusion-matrix

confusionMatrix((factor(N_pred_lassolog)),(factor(N_actual)))
```



